import {
	adpbesuiteIcon,
	androidIcon,
	antdesignIcon,
	appiumIcon,
	awsIcon,
	azureIcon,
	balsamicIcon,
	bitbucketIcon,
	cassandraIcon,
	cypressIcon,
	digitalOceanIcon,
	dockerIcon,
	elkIcon,
	figmaIcon,
	flutterIcon,
	gatsbyIcon,
	gitlabIcon,
	goIcon,
	grafanaIcon,
	gspIcon,
	invisionIcon,
	iosIcon,
	javaIcon,
	jmeterIcon,
	jsIcon,
	kotlinIcon,
	kubernetesIcon,
	lokiIcon,
	lottieIcon,
	materialuiIcon,
	mongodbIcon,
	nextIcon,
	nodejsIcon,
	photoshopIcon,
	phpIcon,
	principleIcon,
	promotheusIcon,
	psqlIcon,
	pythonIcon,
	reactIcon,
	saccIcon,
	sketchIcon,
	swiftIcon,
	terraformIcon,
	vuejsIcon,
	yourtrackIcon,
	zeplinIcon,
} from "@/shared/assets/icons/instruments-icons";

export const TOOLS_CONTENT: Array<string> = [
	"Frontend",
	"Backend",
	"Devops",
	"Testing",
	"UXUI",
	"Infrastructure",
	"Mobile",
];

export const TOOLS_WITH_IMAGE_CONTENT: Array<{
	title: string;
	image: string;
	option: string;
}> = [
	{ title: "Prometheus", image: promotheusIcon, option: "Devops" },
	{ title: "Loki", image: lokiIcon, option: "Devops" },
	{ title: "Bitbucket", image: bitbucketIcon, option: "Devops" },
	{ title: "Gitlab", image: gitlabIcon, option: "Devops" },
	{ title: "Kotlin", image: kotlinIcon, option: "Mobile" },
	{ title: "Android", image: androidIcon, option: "Mobile" },
	{ title: "Java", image: javaIcon, option: "Mobile" },
	{ title: "Azure", image: azureIcon, option: "Infrastructure" },
	{ title: "GCP", image: gspIcon, option: "Infrastructure" },
	{ title: "DigitalOcean", image: digitalOceanIcon, option: "Infrastructure" },
	{ title: "AWS", image: awsIcon, option: "Infrastructure" },
	{ title: "Kubernetes", image: kubernetesIcon, option: "Infrastructure" },
	{ title: "ELK", image: elkIcon, option: "Devops" },
	{ title: "Grafana", image: grafanaIcon, option: "Devops" },
	{ title: "Terraform", image: terraformIcon, option: "Devops" },
	{ title: "iOS", image: iosIcon, option: "Mobile" },
	{ title: "Swift", image: swiftIcon, option: "Mobile" },
	{ title: "Flutter", image: flutterIcon, option: "Mobile" },
	{ title: "Next.JS", image: nextIcon, option: "Frontend" },
	{ title: "React.JS", image: reactIcon, option: "Frontend" },
	{ title: "Javascript", image: jsIcon, option: "Frontend" },
	{ title: "Balsamic", image: balsamicIcon, option: "UXUI" },
	{ title: "Invision", image: invisionIcon, option: "UXUI" },
	{ title: "Figma", image: figmaIcon, option: "UXUI" },
	{ title: "Docker", image: dockerIcon, option: "Devops" },
	{ title: "PostgreSQL", image: psqlIcon, option: "Backend" },
	{ title: "Python", image: pythonIcon, option: "Backend" },
	{ title: "Node.JS", image: nodejsIcon, option: "Backend" },
	{ title: "PHP", image: phpIcon, option: "Backend" },
	{ title: "Go", image: goIcon, option: "Backend" },
	{ title: "Ant Design", image: antdesignIcon, option: "Frontend" },
	{ title: "Gatsby.JS", image: gatsbyIcon, option: "Frontend" },
	{ title: "Vue.JS", image: vuejsIcon, option: "Frontend" },
	{ title: "Principle", image: principleIcon, option: "UXUI" },
	{ title: "Sketch", image: sketchIcon, option: "UXUI" },
	{ title: "Adobe suite", image: adpbesuiteIcon, option: "UXUI" },
	{ title: "YouTrack", image: yourtrackIcon, option: "Testing" },
	{ title: "Appium", image: appiumIcon, option: "Testing" },
	{ title: "Cypress", image: cypressIcon, option: "Testing" },
	{ title: "Jmeter", image: jmeterIcon, option: "Testing" },
	{ title: "MongoDB", image: mongodbIcon, option: "Backend" },
	{ title: "Cassandra", image: cassandraIcon, option: "Backend" },
	{ title: "Sass", image: saccIcon, option: "Frontend" },
	{ title: "Material UI", image: materialuiIcon, option: "Frontend" },
	{ title: "Zeplin", image: zeplinIcon, option: "UXUI" },
	{ title: "Illustrator", image: zeplinIcon, option: "UXUI" },
	{ title: "Lottie", image: lottieIcon, option: "UXUI" },
	{ title: "Photoshop", image: photoshopIcon, option: "UXUI" },
];
